let MDM_CONFIGURATION_KEY = "com.apple.configuration.managed"
let MDM_CACHED_CONFIGURATION_KEY = "com.appconfig.configuration.persisted"
// App Configuration
let MDM_APP_ALLOW_ACCESS = "AppAllowAccess"
let MDM_APP_CERTIFICATE_ALIAS = "AppManagedCertAlias"
let MDM_APP_DEFAULT_BROWSER = "AppDefaultBrowser"
let MDM_APP_DEFAULT_BROWSER_REQUIRED = "AppRequireDefaultBrowser"
// Account Configuration
let MDM_ACCOUNT_CERTIFICATE = "AccountLoginCertificate"
let MDM_ACCOUNT_CERTIFICATE_NAME = "AccountLoginCertificateName"
let MDM_ACCOUNT_DESCRIPTION = "AccountName"
let MDM_ACCOUNT_DISPLAY_NAME = "AccountUserDisplayName"
let MDM_ACCOUNT_EMAIL = "AccountEmail"
let MDM_ACCOUNT_HOST = "AccountServiceHost"
let MDM_ACCOUNT_HOSTS = "AccountServiceHosts"
let MDM_ACCOUNT_PASSWORD = "AccountPassword"
let MDM_ACCOUNT_PORT = "AccountServicePort"
let MDM_ACCOUNT_REQUIRE_CERT_AUTH = "AccountRequireCertAuth"
let MDM_ACCOUNT_SSL = "AccountRequireSSL"
let MDM_ACCOUNT_USERNAME = "AccountUsername"
let MDM_ACCOUNT_USER_DOMAIN = "AccountDomain"
// Policy Configuration
let MDM_APP_ALLOW_FILE_SAVE = "PolicyAllowFileSave"
let MDM_APP_ALLOW_FILE_SAVE_UNENCRYPTED = "PolicyAllowFileSaveUnencrypted"
let MDM_APP_ALLOW_LOGGING = "PolicyAllowLogging"
let MDM_APP_ALLOW_METRICS = "PolicyAllowMetrics"
let MDM_APP_ALLOW_PRINT = "PolicyAllowPrint"
let MDM_APP_ALLOW_SELF_SIGNED_CERTS = "PolicyAllowSelfSignedCerts"
let MDM_APP_ALLOW_SETTINGS_EDIT = "PolicyAllowSettingEdit"
let MDM_APP_OPEN_IN_WHITELIST = "PolicyDocumentSharingWhitelist"
let MDM_APP_RESTRICT_COPY_PASTE = "PolicyRestrictCopyPaste"
let MDM_APP_RESTRICT_OPEN_IN = "PolicyRestrictDocumentSharing"
// App Password Policy
let MDM_APP_PASSCODE_ALLOW_SIMPLE = "AppPasscodeAllowSimple"
let MDM_APP_PASSCODE_ATTEMPTS = "AppPasscodeAttempts"
let MDM_APP_PASSCODE_COMPLEX = "AppPasscodeComplex"
let MDM_APP_PASSCODE_HISTORY = "AppPasscodeHistory"
let MDM_APP_PASSCODE_LENGTH = "AppPasscodeLength"
let MDM_APP_PASSCODE_MAX_AGE = "AppPasscodeMaxAge"
let MDM_APP_PASSCODE_TIMEOUT = "AppPasscodeTimeout"
let MDM_APP_PASSCODE_TYPE = "AppPasscodeType"
// User Configuration
let MDM_USER_GROUP_CODE = "UserGroupCode"
// Branding
let MDM_BRANDING_BACKGROUND = "BrandingBackground"
let MDM_BRANDING_LOGO = "BrandingLogo"
let MDM_BRANDING_NAME = "BrandingName"
// App Tutorial Override
let MDM_APP_SKIP_TUTORIAL = "AppSkipTutorial"

